### ISSUE TITLE
Error: No JSON object could be decoded

### ISSUE THREAD

**Issue by muriloventuroso** [rethinkdb/docs#1077]
RethinkDB installed on a Debian, but I'm getting an error message when connecting by Python 2.7:
`
>>> import rethinkdb as r
>>> r.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 661, in connect
    return conn.reconnect(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 572, in reconnect
    return self._instance.connect(timeout)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 427, in connect
    self._socket = SocketWrapper(self, timeout)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 322, in __init__
    (self.host, self.port, ex))
rethinkdb.errors.ReqlDriverError: Could not connect to localhost:28015. Error: No JSON object could be decoded`
The web interface can access and manipulate the data normally.

**Comment by chipotle** [comment]
Hi, and sorry you're having an issue.You should consider asking about this in the RethinkDB IRC or Slack if you can, or re-opening this ticket in the RethinkDB source code repository -- this is the repository for the documentation.

links to IRC/Slack/etc: http://rethinkdb.com/community/
rethinkdb repo: https://github.com/rethinkdb/rethinkdb

**Comment by muriloventuroso** [comment]
sorry
